version: '3.8'

services:
  app:
    image: 'cinema'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: cinema
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_URL=${POSTGRES_URL}
