version: '2.9'

services:
  app:
    image: 'cinema:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: cinema
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: 'postgres:15.5-alpine'
    ports:
      - "5432:5432"
    container_name: db
    env_file:
      - ./.env