name: CD

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build Docker image
          run: docker-compose build app=cinema:${GITHUB_SHA}

        - name: Push Docker image
          run: docker-compose push