name: CD

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ${{matrix.os}}

    env:
      image_tag: '${{ secrets.DOCKERHUB_USERNAME }}/cinema:${{ secrets.github_sha }}'

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build Docker image
          env:
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          run: docker build -t ${{ env.image_tag }} .

        - name: Push Docker image
          run: docker push ${{ env.image_tag }}